### ISSUE TITLE
Compatibility with the 1.0 spec

### ISSUE THREAD

**Issue by jklmnn** [defgsus/ParkAPI2#14]
I set up a local instance and checked it with my [validator](https://github.com/jklmnn/parkendd-status/blob/master/validate.py) however it returned that the index is not valid. I haven't looked into the details yet however I think this is something we need to fix before a productive use.
@hbruch 

You can validate it by running:
```
./validate.py http://localhost:8000/api/
```

**Comment by hbruch** [comment]
Reason (at least one) is, that ParkAPI2 does not return source for some pools:

```
$ python validate.py http://api.localhost/api
ERROR:root:message
Traceback (most recent call last):
  File ".../parkendd-status/validate.py", line 53, in index_is_valid
    jsonschema.validate(data, self.indexschema)
  File ".../site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: None is not of type 'string'

Failed validating 'type' in schema['properties']['cities']['patternProperties']['[A-Z][a-z]*']['properties']['source']:
    {'type': 'string'}

On instance['cities']['Bielefeld']['source']:
    None
{'status': 200, 'index': 'invalid'}
```

I suggest to return public_url (which should be the url used for scraping) in case no source_url is defined.

**Comment by hbruch** [comment]
Besides this, `last_updated` is not returned and for some parkings `free` is returned with value `None`.
However, the validator' [city_schema](https://github.com/jklmnn/parkendd-status/blob/master/schema_city.json) does not match exactly ParkAPI's [city_schema](https://github.com/offenesdresden/ParkAPI/blob/master/schema/city_schema.json). I.e. ParkAPI1 does not require `free`, while validator does. 

`last_updated` should be returned, and if `free` is unknown, it should not.

```
On instance['last_updated']:
    None
ERROR:root:message
Traceback (most recent call last):
  File ".../parkendd-status/validate.py", line 62, in city_is_valid
    jsonschema.validate(data, self.cityschema)
  File ".../site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: None is not of type 'string'

Failed validating 'type' in schema['properties']['last_updated']:
    {'type': 'string'}

On instance['last_updated']:
    None
ERROR:root:message
Traceback (most recent call last):
  File ".../parkendd-status/validate.py", line 62, in city_is_valid
    jsonschema.validate(data, self.cityschema)
  File ".../site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: None is not of type 'integer'

Failed validating 'type' in schema['properties']['lots']['items']['properties']['free']:
    {'type': 'integer'}

On instance['lots'][1]['free']:
    None
```

**Comment by jklmnn** [comment]
> ParkAPI1 does not require free, while validator does.

We should assume that it does require free, otherwise applications may break. If it creates output that does not include free that is a bug. In the case of nodata free should be set to 0.

> last_updated should be returned, and if free is unknown, it should not.

last_updated is a property of a city while free is a property of a single lot. So we always have to supply last_updated.
